jobs:
  include:
    - stage: absolute_minimum
      name: "Test data loader"
      language: python
      python: 3.6
      script:
        - cd test/code/preprocessing
        - pytest test_data_loader.py
        - cd ../../..
    - stage: absolute_minimum
      name: "Test TensorFlow classifier"
      language: python
      python: 3.6
      script:
        - cd test/code/tensorflow
        - pytest test_tf_classifier.py
        - cd ../../..
    - stage: absolute_minimum
      name: "Test Keras classifier"
      language: python
      python: 3.6
      script:
        - cd test/code/keras
        - pytest test_keras_classifier.py
    - stage: absolute_minimum
      name: "Test Keras regressor"
      language: python
      python: 3.6
      script:
      - cd test/code/keras
      - pytest test_keras_regressor.py
    - stage: main_task
      name: "Test RNN"
      language: python
      python: 3.6
      script:
        - echo "TBD"
    - stage: main_task
      name: "Test FastText"
      language: python
      python: 3.6
      script:
        - echo "TBD"
    - stage: main_task
      name: "Test NN with pre-trained W2V"
      language: python
      python: 3.6
      script:
        - echo "TBD"
    - stage: extented_task
      name: "Extended task"
      language: python
      python: 3.6
      script:
        - echo "TBD"